AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
Metrics/MethodLength:
  Enabled: true
  Max: 15
Metrics/AbcSize:
  Enabled: true
  Max: 25
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 10
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 10
Style/Documentation:
   Enabled: false
